config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledge/concepts#index'

  namespace :curriculum, shallow: true do
    resources :boards do
      resources :subjects do
        resources :branches do
          resources :chapters do
            resources :sections do
              resources :learning_skills, controller: :sections_learning_skills
            end

            resources :sections_learning_skills, only: :destroy
          end
        end
      end
    end
  end

  namespace :learning, shallow: true do
    resources :skills do
      resources :knowledge_concepts, controller: :skills_knowledge_concepts
    end

    resources :skills_knowledge_concepts, only: :destroy
  end

  namespace :knowledge, shallow: true do
    resources :concepts do
      resources :skills, controller: :concepts_learning_skills
    end
  end

  resources :data_uploads, only: %i[new create]

  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
end

app/controllers/data_uploads_controller.rb
class DataUploadsController < ApplicationController
  def new
    @uploader = DataUploadService.new
  end

  def create
    @uploader = DataUploadService.new(uploader_params[:file])
    send_file @uploader.execute
  end

  private

  def uploader_params
    params.require(:uploader).permit(:file)
  end
end

app/helpers/data_uploads_helper.rb
module DataUploadsHelper
end

app/views/data_uploads/new.html.slim
h2 Curriculum, Learning, and Knowledge data

b Guidelines
ol
  li The format of the file should be csv
  li The structure of the csv should be as follows:
.table-responsive
  table.table.table-striped
    thead
      tr
        th Board
        th Subject
        th Branch
        th Chapter
        th Section
        th Skill
        th Grade
        th Concept(s)
    tbody
      tr
        td CBSE
        td Physics
        td Optics
        td Reflection on Curved Surfaces
        td Concave Surfaces
        td Identify a concave mirror
        td 10
        td mirror, curve, concave

= simple_form_for @uploader, as: :uploader, method: :post, url: data_uploads_path do |f|
  = f.file_field :file, required: true
  = f.submit 'Upload'

p After uploading, a new csv file will be downloaded with an extra column showing the errors