config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledge/concepts#index'

  namespace :curriculum, shallow: true do
    resources :boards do
      resources :subjects do
        resources :branches do
          resources :chapters do
            resources :sections do
              resources :learning_skills, controller: :sections_learning_skills
            end

            resources :sections_learning_skills, only: :destroy
          end
        end
      end
    end
  end

  namespace :learning, shallow: true do
    resources :skills do
      resources :knowledge_concepts, controller: :skills_knowledge_concepts
    end

    resources :skills_knowledge_concepts, only: :destroy
  end

  namespace :knowledge, shallow: true do
    resources :concepts do
      resources :skills, controller: :concepts_learning_skills
    end
  end

  resources :data_uploads, only: %i[new create]

  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
end

app/models/concerns/learning/skills/body_validator.rb
# frozen_string_literal: true

module Learning
  module Skills
    class BodyValidator < ActiveModel::Validator
      module ValidStartingPhrases
        IDENTIFY = 'identify'
        STATE = 'state'
        FIND = 'find'
        APPLY = 'apply'
        USE = 'use'
        REPRESENT = 'represent'
        VERIFY = 'verify'
        PROVE = 'prove'
        CONVERT = 'convert'
        CLASSIFY = 'classify'
        DRAW = 'draw'
        WRITE = 'write'
        LOCATE = 'locate'

        include AllConstantsAsAll
      end

      def validate(skill)
        return if skill.body.start_with? *ValidStartingPhrases::ALL

        skill.errors[:body] <<
          'can only start with '\
          'any of the following phrases: '\
          "#{ValidStartingPhrases::ALL.join(', ')}"
      end
    end
  end
end

app/models/learning.rb
module Learning
  def self.table_name_prefix
    'learning_'
  end
end

app/models/learning/skill.rb
# frozen_string_literal: true

class Learning::Skill < ApplicationRecord
  has_many :skills_knowledge_concepts,
           dependent: :destroy

  has_many :knowledge_concepts,
           through: :skills_knowledge_concepts

  has_many :curriculum_sections_learning_skills,
           class_name: 'Curriculum::SectionsLearningSkill',
           foreign_key: :learning_skill_id,
           dependent: :destroy

  has_many :curriculum_sections,
           through: :curriculum_sections_learning_skills,
           source: :section, class_name: 'Curriculum::Section'

  # validates_with Learning::Skills::BodyValidator
end

app/models/learning/skills_knowledge_concept.rb
# frozen_string_literal: true

class Learning::SkillsKnowledgeConcept < ApplicationRecord
  belongs_to :skill
  belongs_to :knowledge_concept, class_name: 'Knowledge::Concept'

  validate :skill_body_should_be_valid
  validate :knowledge_concept_title_should_be_valid

  validates :skill,             uniqueness: { scope: :knowledge_concept }
  validates :knowledge_concept, uniqueness: { scope: :skill }

  validate :skill_knowledge_concept_mapping_should_be_unique

  def skill_body
    skill&.body
  end

  def skill_body=(new_body)
    self.skill = Learning::Skill.create_or_find_by(body: new_body)
    skill.body
  end

  def knowledge_concept_title
    knowledge_concept&.title
  end

  def knowledge_concept_title=(new_title)
    self.knowledge_concept = Knowledge::Concept.create_or_find_by(title: new_title)
    knowledge_concept.title
  end

  private

  def skill_body_should_be_valid
    skill.errors[:body].each { |e| errors[:skill_body] << e }
  end

  def knowledge_concept_title_should_be_valid
    knowledge_concept.errors[:title].each { |e| errors[:knowledge_concept_title] << e }
  end

  def skill_knowledge_concept_mapping_should_be_unique
    errors[:skill].each             { |e| errors[:skill_body] << e }
    errors[:knowledge_concept].each { |e| errors[:knowledge_concept_title] << e }
  end
end

app/controllers/learning/skills_controller.rb
class Learning::SkillsController < ApplicationController
  before_action :set_learning_skill, only: [:show, :edit, :update, :destroy]

  # GET /learning/skills
  # GET /learning/skills.json
  def index
    @learning_skills = Learning::Skill.all
  end

  # GET /learning/skills/1
  # GET /learning/skills/1.json
  def show
  end

  # GET /learning/skills/new
  def new
    @learning_skill = Learning::Skill.new
  end

  # GET /learning/skills/1/edit
  def edit
  end

  # POST /learning/skills
  # POST /learning/skills.json
  def create
    @learning_skill = Learning::Skill.new(learning_skill_params)

    respond_to do |format|
      if @learning_skill.save
        format.html { redirect_to @learning_skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @learning_skill }
      else
        format.html { render :new }
        format.json { render json: @learning_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learning/skills/1
  # PATCH/PUT /learning/skills/1.json
  def update
    respond_to do |format|
      if @learning_skill.update(learning_skill_params)
        format.html { redirect_to @learning_skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @learning_skill }
      else
        format.html { render :edit }
        format.json { render json: @learning_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learning/skills/1
  # DELETE /learning/skills/1.json
  def destroy
    @learning_skill.destroy
    respond_to do |format|
      format.html { redirect_to learning_skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learning_skill
      @learning_skill = Learning::Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def learning_skill_params
      params.require(:learning_skill).permit(:body, :description)
    end
end

app/controllers/learning/skills_knowledge_concepts_controller.rb
class Learning::SkillsKnowledgeConceptsController < ApplicationController
  
  def new
    @skill = Learning::Skill.find params[:skill_id]
    @skills_knowledge_concept = @skill.skills_knowledge_concepts.new
  end

  def create
    @skill = Learning::Skill.find params[:skill_id]

    @skills_knowledge_concept = @skill.skills_knowledge_concepts.new(skills_knowledge_concept_params)

    respond_to do |format|
      if @skills_knowledge_concept.save
        format.html {
          redirect_to learning_skill_knowledge_concepts_path(@skill),
          notice: 'Skill was successfully created.'
        }
        format.json { render :show, status: :created, location: @skills_knowledge_concept }
      else
        format.html { render :new }
        format.json { render json: @skills_knowledge_concept.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @skill = Learning::Skill.find params[:skill_id]
    @skills_knowledge_concepts = @skill.skills_knowledge_concepts
  end

  def destroy
    Learning::SkillsKnowledgeConcept.find(params[:id]).destroy
    redirect_back fallback_location: root_path, notice: 'Skill was successfully removed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def skills_knowledge_concept_params
    params.require(:learning_skills_knowledge_concept).permit(:knowledge_concept_title)
  end
end

app/helpers/learning/skills_helper.rb
module Learning::SkillsHelper
end

app/views/learning/skills_knowledge_concepts/_form.html.slim
= simple_form_for([@skill, @skills_knowledge_concept], url: :learning_skill_knowledge_concepts) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :knowledge_concept_title, autofocus: true, input_html: { list: :knowledge_concept_titles, autocomplete: 'off' }

  datalist#knowledge_concept_titles
    = options_for_select((Knowledge::Concept.all - @skill.knowledge_concepts).pluck(:title))

  == render 'forms/navigation', f: f, back_to: back_to

app/views/learning/skills_knowledge_concepts/_index_table.html.slim
.table-responsive
  table.table.table-striped
    thead
      tr
        th Title
        th Description
        th
        th
        th
        th

    tbody
      - skills_knowledge_concepts.each do |skills_knowledge_concept|
        tr
          td = skills_knowledge_concept.knowledge_concept.title
          td = skills_knowledge_concept.knowledge_concept.description
          td = link_to "#{skills_knowledge_concept.knowledge_concept.concepts_learning_skills.count} learning skills",
                       knowledge_concept_skills_path(skills_knowledge_concept.knowledge_concept)
          td = link_to 'Show', skills_knowledge_concept.knowledge_concept
          td = link_to 'Edit', edit_knowledge_concept_path(skills_knowledge_concept.knowledge_concept)
          td = link_to "Remove from #{skill.body}",
                       skills_knowledge_concept,
                       data: { confirm: 'Are you sure?' },
                       method: :delete

app/views/learning/skills_knowledge_concepts/index.html.slim
h3 Listing concepts related to
h1 #{@skill.body}

= link_to 'Add a concept', new_learning_skill_knowledge_concept_path
br/
br/

== render 'index_table',
          skills_knowledge_concepts: @skills_knowledge_concepts,
          skill: @skill
br

= link_to 'Add a concept', new_learning_skill_knowledge_concept_path

app/views/learning/skills_knowledge_concepts/new.html.slim
h1 Add a concept to #{@skill.body}

== render 'form', back_to: learning_skill_knowledge_concepts_path(@skill)