config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledge/concepts#index'

  namespace :curriculum, shallow: true do
    resources :boards do
      resources :subjects do
        resources :branches do
          resources :chapters do
            resources :sections do
              resources :learning_skills, controller: :sections_learning_skills
            end

            resources :sections_learning_skills, only: :destroy
          end
        end
      end
    end
  end

  namespace :learning, shallow: true do
    resources :skills do
      resources :knowledge_concepts, controller: :skills_knowledge_concepts
    end

    resources :skills_knowledge_concepts, only: :destroy
  end

  namespace :knowledge, shallow: true do
    resources :concepts do
      resources :skills, controller: :concepts_learning_skills
    end
  end

  resources :data_uploads, only: %i[new create]

  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
end

app/models/knowledge.rb
module Knowledge
  def self.table_name_prefix
    'knowledge_'
  end
end

app/models/knowledge/concept.rb
class Knowledge::Concept < ApplicationRecord

  has_many :concepts_learning_skills,
           class_name: 'Learning::SkillsKnowledgeConcept',
           foreign_key: :knowledge_concept_id,
           dependent: :destroy

  has_many :learning_skills,
           through: :concepts_learning_skills,
           source: :skill, class_name: 'Learning::Skill'

  has_many :curriculum_sections,
           through: :learning_skills
end

app/controllers/knowledge/concepts_controller.rb
class Knowledge::ConceptsController < ApplicationController
  before_action :set_knowledge_concept, only: [:show, :edit, :update, :destroy]

  # GET /knowledge/concepts
  # GET /knowledge/concepts.json
  def index
    @knowledge_concepts = Knowledge::Concept.all
  end

  # GET /knowledge/concepts/1
  # GET /knowledge/concepts/1.json
  def show
  end

  # GET /knowledge/concepts/new
  def new
    @knowledge_concept = Knowledge::Concept.new
  end

  # GET /knowledge/concepts/1/edit
  def edit
  end

  # POST /knowledge/concepts
  # POST /knowledge/concepts.json
  def create
    @knowledge_concept = Knowledge::Concept.new(knowledge_concept_params)

    respond_to do |format|
      if @knowledge_concept.save
        format.html { redirect_to @knowledge_concept, notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge_concept }
      else
        format.html { render :new }
        format.json { render json: @knowledge_concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledge/concepts/1
  # PATCH/PUT /knowledge/concepts/1.json
  def update
    respond_to do |format|
      if @knowledge_concept.update(knowledge_concept_params)
        format.html { redirect_to @knowledge_concept, notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge_concept }
      else
        format.html { render :edit }
        format.json { render json: @knowledge_concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledge/concepts/1
  # DELETE /knowledge/concepts/1.json
  def destroy
    @knowledge_concept.destroy
    respond_to do |format|
      format.html { redirect_to knowledge_concepts_url, notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge_concept
      @knowledge_concept = Knowledge::Concept.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def knowledge_concept_params
      params.require(:knowledge_concept).permit(:title, :description)
    end
end

app/controllers/knowledge/concepts_learning_skills_controller.rb
# frozen_string_literal: true

class Knowledge::ConceptsLearningSkillsController < ApplicationController
  def new
    @concept = Knowledge::Concept.find params[:concept_id]
    @concepts_learning_skill = @concept.concepts_learning_skills.new
  end

  def create
    @concept = Knowledge::Concept.find params[:concept_id]

    @concepts_learning_skill = @concept.concepts_learning_skills.new(concepts_learning_skill_params)

    respond_to do |format|
      if @concepts_learning_skill.save
        format.html {
          redirect_to knowledge_concept_skills_path(@concept),
          notice: 'Skill was successfully created.'
        }
        format.json { render :show, status: :created, location: @concepts_learning_skill }
      else
        format.html { render :new }
        format.json { render json: @concepts_learning_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @concept = Knowledge::Concept.find params[:concept_id]
    @concepts_learning_skills = @concept.concepts_learning_skills
  end

  private

  # Only allow a list of trusted parameters through.
  def concepts_learning_skill_params
    params.require(:learning_skills_knowledge_concept).permit(:skill_body)
  end
end

app/helpers/knowledge/concepts_helper.rb
module Knowledge::ConceptsHelper
end

app/views/knowledge/concepts_learning_skills/_form.html.slim
= simple_form_for([@concept, @concepts_learning_skill], url: :knowledge_concept_skills) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :skill_body, autofocus: true, input_html: { list: :skill_bodies, autocomplete: 'off' }

  datalist#skill_bodies
    = options_for_select((Learning::Skill.all - @concept.learning_skills).pluck(:body))

  == render 'forms/navigation', f: f, back_to: back_to

app/views/knowledge/concepts_learning_skills/_index_table.html.slim
.table-responsive
  table.table.table-striped
    thead
      tr
        th Body
        th Description
        th
        th
        th

    tbody
      - concepts_learning_skills.each do |concepts_learning_skill|
        tr
          td = concepts_learning_skill.skill.body
          td = concepts_learning_skill.skill.description
          td = link_to 'Show', concepts_learning_skill.skill
          td = link_to 'Edit', edit_learning_skill_path(concepts_learning_skill.skill)
          td = link_to "Remove from #{concept.title}",
                       concepts_learning_skill,
                       data: { confirm: 'Are you sure?' },
                       method: :delete

app/views/knowledge/concepts_learning_skills/index.html.slim
h1 Listing skills related to #{@concept.title}

= link_to 'Add a skill', new_knowledge_concept_skill_path
br
br

== render 'index_table',
          concepts_learning_skills: @concepts_learning_skills,
          concept: @concept
br

= link_to 'Add a skill', new_knowledge_concept_skill_path

app/views/knowledge/concepts_learning_skills/new.html.slim
h1 Add a skill to #{@concept.title}

== render 'form', back_to: knowledge_concept_skills_path(@concept)